version: '3.8'
services:
  nginx: 
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - dev_network

  php:
    build:
      context: ./
      dockerfile: DockerFile
    tty: true
    container_name: php
    volumes:
      - ./:/var/www/html
    networks:
      - dev_network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: edwin
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    tmpfs:
      - /var/run/mysqld:rw,noexec,nosuid,nodev,size=65536k,mode=0755
    networks:
      - dev_network
    
volumes:
  db_data:

networks:
  dev_network:
    driver: bridge